import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import path from "node:path";
import test from "node:test";

import {
  resolveWorkShellInputAction,
  resolveWorkShellSubmitAction,
} from "../../packages/tui/src/work-shell-input.ts";

const INPUT_BOOLEAN_FIELDS = [
  "ctrlC",
  "tab",
  "shift",
  "upArrow",
  "downArrow",
  "escape",
  "slashOpen",
  "isBusy",
  "hasRequestSessionsView",
  "hasSensitiveInput",
  "hasOverlayOpen",
  "hasSlashPicker",
  "inputNonEmpty",
  "escapeResetArmed",
];

// Golden outputs generated by a freshly built `unclecode rust ux` reference.
// These compact hashes let the regular Node suite replay the exhaustive
// matrix without spawning 16,832 child processes on every run.
// Reproduce against the live Rust owner with:
//   cargo build -p unclecode && UNCLECODE_VERIFY_RUST_INPUT_PARITY=1 \
//     node --conditions=source --import tsx --test <this-file>
const RUST_PARITY_HASHES = {
  input: "12fc8117a533b996d53119fe43f03ae70d69c003b81d44727c168d6abde0b6df",
  modes: "94def875116c65fa7dede97b79becb70fc829ee2e898670cc5dca8754d6f6080",
  selected: "762b56cce70882423305e9c1efcf8672c031c2d7047a81be94a36183cb18e0f8",
  submit: "431193398fcf8a66f111c3c3197a3750bbc19255190c6c428f544e2044d21b43",
  whitespace: "feeba217bcd878bcc9effe747b260aaf97f2dc7b8c6c467e6e48a7c022e7e09d",
};

const VERIFY_LIVE_RUST = process.env.UNCLECODE_VERIFY_RUST_INPUT_PARITY === "1";
const RUST_BINARY = process.env.UNCLECODE_RUST_BIN
  ?? path.resolve("target", "debug", "unclecode");

const RUST_WHITESPACE_AND_JS_ONLY_BOM = [
  "\u0009", "\u000A", "\u000B", "\u000C", "\u000D", "\u0020", "\u0085", "\u00A0",
  "\u1680", "\u2000", "\u2001", "\u2002", "\u2003", "\u2004", "\u2005", "\u2006",
  "\u2007", "\u2008", "\u2009", "\u200A", "\u2028", "\u2029", "\u202F", "\u205F",
  "\u3000", "\uFEFF",
];

function canonicalAction(action) {
  return JSON.stringify(action, Object.keys(action).sort());
}

function hashActions(fixtures) {
  const hash = createHash("sha256");
  for (const { id, action } of fixtures) {
    hash.update(`${id}:${canonicalAction(action)}\n`);
  }
  return hash.digest("hex");
}

function resolveRustAction(kind, input) {
  const result = spawnSync(RUST_BINARY, ["rust", "ux", kind], {
    cwd: process.cwd(),
    input: JSON.stringify(input),
    encoding: "utf8",
  });
  assert.equal(result.status, 0, result.stderr || `Could not run ${RUST_BINARY}`);
  return JSON.parse(result.stdout);
}

function resolveInputAction(input) {
  const action = resolveWorkShellInputAction(input);
  if (VERIFY_LIVE_RUST) {
    assert.deepEqual(action, resolveRustAction("input-action", input));
  }
  return action;
}

function resolveSubmitAction(input) {
  const action = resolveWorkShellSubmitAction(input);
  if (VERIFY_LIVE_RUST) {
    assert.deepEqual(action, resolveRustAction("submit-action", input));
  }
  return action;
}

function buildBooleanInputFixture(mask) {
  const on = Object.fromEntries(
    INPUT_BOOLEAN_FIELDS.map((name, index) => [name, Boolean(mask & 2 ** index)]),
  );
  return {
    value: on.ctrlC ? "c" : "",
    key: {
      ...(on.ctrlC ? { ctrl: true } : {}),
      ...(on.tab ? { tab: true } : {}),
      ...(on.shift ? { shift: true } : {}),
      ...(on.upArrow ? { upArrow: true } : {}),
      ...(on.downArrow ? { downArrow: true } : {}),
      ...(on.escape ? { escape: true } : {}),
    },
    input: on.slashOpen ? "/auth" : (on.inputNonEmpty ? "plain" : ""),
    slashSuggestionCount: on.slashOpen ? 1 : 0,
    selectedSlashCommand: "/auth status",
    isBusy: on.isBusy,
    hasRequestSessionsView: on.hasRequestSessionsView,
    currentMode: "default",
    hasSensitiveInput: on.hasSensitiveInput,
    hasOverlayOpen: on.hasOverlayOpen,
    hasSlashPicker: on.hasSlashPicker,
    escapeResetArmed: on.escapeResetArmed,
  };
}

test("work-shell input routing matches the exhaustive Rust precedence fixture", () => {
  const fixtures = Array.from({ length: 2 ** INPUT_BOOLEAN_FIELDS.length }, (_, mask) => ({
    id: String(mask),
    action: resolveInputAction(buildBooleanInputFixture(mask)),
  }));

  assert.equal(hashActions(fixtures), RUST_PARITY_HASHES.input);
  assert.deepEqual(
    [...new Set(fixtures.map(({ action }) => canonicalAction(action)))].sort(),
    [
      { type: "none" },
      { type: "exit" },
      { type: "interrupt-turn" },
      { type: "cycle-mode", nextMode: "yolo" },
      { type: "complete-slash", value: "/auth status " },
      { type: "move-slash-selection", direction: "previous" },
      { type: "move-slash-selection", direction: "next" },
      { type: "cancel-sensitive-input" },
      { type: "close-slash-picker" },
      { type: "close-overlay" },
      { type: "clear-input" },
      { type: "open-engine-sessions" },
    ].map(canonicalAction).sort(),
  );
});

test("work-shell mode and slash-completion properties match Rust fixtures", () => {
  const modes = [undefined, "", "default", "yolo", "ultrawork", "analyze", "search", "unknown"];
  const modeFixtures = modes.map((currentMode, index) => ({
    id: String(index),
    action: resolveInputAction({
      value: "",
      key: { tab: true, shift: true },
      input: "plain",
      slashSuggestionCount: 0,
      isBusy: false,
      hasRequestSessionsView: false,
      ...(currentMode === undefined ? {} : { currentMode }),
    }),
  }));
  const selections = [undefined, "", "/auth status", " 한글 "];
  const selectionFixtures = selections.map((selectedSlashCommand, index) => ({
    id: String(index),
    action: resolveInputAction({
      value: "",
      key: { tab: true },
      input: " /auth ",
      slashSuggestionCount: 1,
      isBusy: false,
      hasRequestSessionsView: false,
      ...(selectedSlashCommand === undefined ? {} : { selectedSlashCommand }),
    }),
  }));

  assert.equal(hashActions(modeFixtures), RUST_PARITY_HASHES.modes);
  assert.equal(hashActions(selectionFixtures), RUST_PARITY_HASHES.selected);
});

test("work-shell submit routing matches the exhaustive Rust action fixture", () => {
  const values = ["", " ", "  ship it  ", "/auth", " /auth ", "gkdl", "/model gpt-5.5", "한글"];
  const selections = [undefined, "", "/auth status"];
  const panels = [undefined, "", "Model picker", "Auth"];
  const fixtures = [];
  for (const [valueIndex, value] of values.entries()) {
    for (const isBusy of [false, true]) {
      for (const shouldBlockSlashSubmit of [false, true]) {
        for (const [selectionIndex, selectedSlashCommand] of selections.entries()) {
          for (const [panelIndex, activePanelTitle] of panels.entries()) {
            fixtures.push({
              id: `${valueIndex}-${Number(isBusy)}-${Number(shouldBlockSlashSubmit)}-${selectionIndex}-${panelIndex}`,
              action: resolveSubmitAction({
                value,
                isBusy,
                shouldBlockSlashSubmit,
                ...(selectedSlashCommand === undefined ? {} : { selectedSlashCommand }),
                ...(activePanelTitle === undefined ? {} : { activePanelTitle }),
              }),
            });
          }
        }
      }
    }
  }

  assert.equal(fixtures.length, 384);
  assert.equal(hashActions(fixtures), RUST_PARITY_HASHES.submit);
  assert.deepEqual(
    [...new Set(fixtures.map(({ action }) => action.type))].sort(),
    ["noop", "submit", "submit-suggestion"],
  );
});

test("work-shell input routing uses Rust Unicode whitespace semantics", () => {
  assert.deepEqual(
    resolveInputAction({
      value: "",
      key: { tab: true },
      input: "\u0085/auth\u0085",
      slashSuggestionCount: 1,
      selectedSlashCommand: "/auth status",
      isBusy: false,
      hasRequestSessionsView: false,
    }),
    { type: "complete-slash", value: "/auth status " },
  );
  assert.deepEqual(
    resolveInputAction({
      value: "",
      key: { tab: true },
      input: "\uFEFF/auth\uFEFF",
      slashSuggestionCount: 1,
      selectedSlashCommand: "/auth status",
      isBusy: false,
      hasRequestSessionsView: false,
    }),
    { type: "none" },
  );
});

test("work-shell slash routing accepts only counts representable as Rust i64 values", () => {
  const base = {
    value: "",
    key: { tab: true },
    input: "/auth",
    selectedSlashCommand: "/auth status",
    isBusy: false,
    hasRequestSessionsView: false,
  };

  assert.deepEqual(
    resolveInputAction({ ...base, slashSuggestionCount: 0.5 }),
    { type: "none" },
  );
  assert.deepEqual(
    resolveInputAction({ ...base, slashSuggestionCount: 2 ** 63 }),
    { type: "none" },
  );
  assert.deepEqual(
    resolveInputAction({ ...base, slashSuggestionCount: 1 }),
    { type: "complete-slash", value: "/auth status " },
  );
});

test("work-shell submit routing uses Rust Unicode whitespace semantics", () => {
  assert.deepEqual(
    resolveSubmitAction({
      value: "\u0085/auth\u0085",
      isBusy: false,
      shouldBlockSlashSubmit: true,
      selectedSlashCommand: "/auth status",
    }),
    { type: "submit", line: "/auth", clearInput: true },
  );
  assert.deepEqual(
    resolveSubmitAction({
      value: "\uFEFF/auth\uFEFF",
      isBusy: false,
      shouldBlockSlashSubmit: true,
      selectedSlashCommand: "/auth status",
    }),
    { type: "submit-suggestion", line: "/auth status", clearInput: true },
  );
});

test("work-shell routing matches Rust across every Unicode whitespace boundary", () => {
  const fixtures = [];
  for (const [index, whitespace] of RUST_WHITESPACE_AND_JS_ONLY_BOM.entries()) {
    fixtures.push({
      id: `input-${index}`,
      action: resolveInputAction({
        value: "",
        key: { tab: true },
        input: `${whitespace}/auth${whitespace}`,
        slashSuggestionCount: 1,
        selectedSlashCommand: "/auth status",
        isBusy: false,
        hasRequestSessionsView: false,
      }),
    });
    fixtures.push({
      id: `submit-${index}`,
      action: resolveSubmitAction({
        value: `${whitespace}/auth${whitespace}`,
        isBusy: false,
        shouldBlockSlashSubmit: true,
        selectedSlashCommand: "/auth status",
      }),
    });
  }

  assert.equal(fixtures.length, 52);
  assert.equal(hashActions(fixtures), RUST_PARITY_HASHES.whitespace);
});
