import {
  describeReasoning,
  getWorkShellSlashSuggestions,
  listSessionLines,
  persistWorkShellSessionSnapshot,
  resolveComposerInput,
  resolveModelCommand,
  resolveReasoningCommand,
  resolveWorkShellSlashCommand,
  shouldBlockSlashSubmit,
} from "@unclecode/orchestrator";
import {
  listAvailableSkills,
  listProjectBridgeLines,
  listScopedMemoryLines,
  loadNamedSkill,
  publishContextBridge,
  writeScopedMemory,
} from "@unclecode/context-broker";
import { getSessionStoreRoot } from "@unclecode/session-store";
import {
  buildAttachmentPreviewLines,
  buildContextPanel,
  buildInlineCommandPanel,
  buildSlashSuggestionPanel,
  buildTerminalInlineImageSequence,
  clampWorkShellSlashSelection,
  createWorkShellDashboardHomePatch,
  createWorkShellDashboardHomeSyncState,
  cycleWorkShellSlashSelection,
  extractAuthLabel,
  formatAgentTraceLine,
  formatAttachmentBadgeLine,
  formatAuthLabelForDisplay,
  formatInlineImageSupportLine,
  formatInlineCommandResultSummary,
  formatRuntimeLabel,
  formatToolTraceLine,
  formatWorkShellError,
  getWorkShellConversationLayout,
  refineInlineCommandPanelLines,
  resolveWorkShellActivePanel,
  resolveWorkShellInputAction,
  resolveWorkShellSubmitAction,
  shouldRefreshDashboardHomeState,
} from "@unclecode/tui";

export type { StartReplOptions } from "../apps/unclecode-cli/src/work-runtime.js";
export {
  resolveWorkShellInlineCommand,
  createWorkShellDashboardProps,
  startRepl,
} from "../apps/unclecode-cli/src/work-runtime.js";

export {
  buildAttachmentPreviewLines,
  buildContextPanel,
  buildInlineCommandPanel,
  buildSlashSuggestionPanel,
  clampWorkShellSlashSelection,
  createWorkShellDashboardHomePatch,
  createWorkShellDashboardHomeSyncState,
  cycleWorkShellSlashSelection,
  describeReasoning,
  extractAuthLabel,
  formatAgentTraceLine,
  formatAttachmentBadgeLine,
  formatAuthLabelForDisplay,
  formatInlineImageSupportLine,
  formatInlineCommandResultSummary,
  formatRuntimeLabel,
  formatToolTraceLine,
  formatWorkShellError,
  getWorkShellConversationLayout as getConversationLayout,
  getWorkShellSlashSuggestions,
  getSessionStoreRoot,
  listAvailableSkills,
  listProjectBridgeLines,
  listScopedMemoryLines,
  listSessionLines,
  loadNamedSkill,
  persistWorkShellSessionSnapshot,
  publishContextBridge,
  refineInlineCommandPanelLines,
  resolveComposerInput,
  resolveModelCommand,
  resolveReasoningCommand,
  resolveWorkShellActivePanel,
  resolveWorkShellInputAction,
  resolveWorkShellSlashCommand,
  resolveWorkShellSubmitAction,
  shouldBlockSlashSubmit,
  shouldRefreshDashboardHomeState,
  writeScopedMemory,
  buildTerminalInlineImageSequence,
};
